// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: api/oms.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderStatus int32

const (
	OrderStatus_UNKNOWN   OrderStatus = 0
	OrderStatus_PENDING   OrderStatus = 1
	OrderStatus_COMPLETED OrderStatus = 2
	OrderStatus_CANCELED  OrderStatus = 3
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "PENDING",
		2: "COMPLETED",
		3: "CANCELED",
	}
	OrderStatus_value = map[string]int32{
		"UNKNOWN":   0,
		"PENDING":   1,
		"COMPLETED": 2,
		"CANCELED":  3,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_oms_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_api_oms_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_oms_proto_rawDescGZIP(), []int{0}
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	CustomerID    string                 `protobuf:"bytes,2,opt,name=customerID,proto3" json:"customerID,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=Status,proto3" json:"Status,omitempty"`
	Items         []*Item                `protobuf:"bytes,4,rep,name=Items,proto3" json:"Items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_api_oms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_api_oms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_api_oms_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Order) GetCustomerID() string {
	if x != nil {
		return x.CustomerID
	}
	return ""
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Order) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	PriceID       string                 `protobuf:"bytes,4,opt,name=PriceID,proto3" json:"PriceID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_api_oms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_api_oms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_api_oms_proto_rawDescGZIP(), []int{1}
}

func (x *Item) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Item) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetPriceID() string {
	if x != nil {
		return x.PriceID
	}
	return ""
}

type ItemWithQuantity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemWithQuantity) Reset() {
	*x = ItemWithQuantity{}
	mi := &file_api_oms_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemWithQuantity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemWithQuantity) ProtoMessage() {}

func (x *ItemWithQuantity) ProtoReflect() protoreflect.Message {
	mi := &file_api_oms_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemWithQuantity.ProtoReflect.Descriptor instead.
func (*ItemWithQuantity) Descriptor() ([]byte, []int) {
	return file_api_oms_proto_rawDescGZIP(), []int{2}
}

func (x *ItemWithQuantity) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *ItemWithQuantity) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerID    string                 `protobuf:"bytes,1,opt,name=customerID,proto3" json:"customerID,omitempty"`
	Items         []*ItemWithQuantity    `protobuf:"bytes,2,rep,name=Items,proto3" json:"Items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_api_oms_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_oms_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_oms_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOrderRequest) GetCustomerID() string {
	if x != nil {
		return x.CustomerID
	}
	return ""
}

func (x *CreateOrderRequest) GetItems() []*ItemWithQuantity {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_api_oms_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_oms_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_oms_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrderRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type GetUserOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerID    string                 `protobuf:"bytes,1,opt,name=customerID,proto3" json:"customerID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserOrdersRequest) Reset() {
	*x = GetUserOrdersRequest{}
	mi := &file_api_oms_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserOrdersRequest) ProtoMessage() {}

func (x *GetUserOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_oms_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserOrdersRequest.ProtoReflect.Descriptor instead.
func (*GetUserOrdersRequest) Descriptor() ([]byte, []int) {
	return file_api_oms_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserOrdersRequest) GetCustomerID() string {
	if x != nil {
		return x.CustomerID
	}
	return ""
}

type GetUserOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=Orders,proto3" json:"Orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserOrdersResponse) Reset() {
	*x = GetUserOrdersResponse{}
	mi := &file_api_oms_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserOrdersResponse) ProtoMessage() {}

func (x *GetUserOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_oms_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserOrdersResponse.ProtoReflect.Descriptor instead.
func (*GetUserOrdersResponse) Descriptor() ([]byte, []int) {
	return file_api_oms_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type PatchOrderStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderID       string                 `protobuf:"bytes,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
	Status        OrderStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=api.OrderStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchOrderStatusRequest) Reset() {
	*x = PatchOrderStatusRequest{}
	mi := &file_api_oms_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchOrderStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchOrderStatusRequest) ProtoMessage() {}

func (x *PatchOrderStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_oms_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchOrderStatusRequest.ProtoReflect.Descriptor instead.
func (*PatchOrderStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_oms_proto_rawDescGZIP(), []int{7}
}

func (x *PatchOrderStatusRequest) GetOrderID() string {
	if x != nil {
		return x.OrderID
	}
	return ""
}

func (x *PatchOrderStatusRequest) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_UNKNOWN
}

type StockItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	PriceID       string                 `protobuf:"bytes,4,opt,name=PriceID,proto3" json:"PriceID,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=Description,proto3" json:"Description,omitempty"`
	ImgPath       string                 `protobuf:"bytes,6,opt,name=ImgPath,proto3" json:"ImgPath,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockItem) Reset() {
	*x = StockItem{}
	mi := &file_api_oms_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockItem) ProtoMessage() {}

func (x *StockItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_oms_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockItem.ProtoReflect.Descriptor instead.
func (*StockItem) Descriptor() ([]byte, []int) {
	return file_api_oms_proto_rawDescGZIP(), []int{8}
}

func (x *StockItem) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *StockItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *StockItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StockItem) GetPriceID() string {
	if x != nil {
		return x.PriceID
	}
	return ""
}

func (x *StockItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *StockItem) GetImgPath() string {
	if x != nil {
		return x.ImgPath
	}
	return ""
}

func (x *StockItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *StockItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type BookedItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingID     string                 `protobuf:"bytes,1,opt,name=BookingID,proto3" json:"BookingID,omitempty"`
	ItemID        string                 `protobuf:"bytes,2,opt,name=ItemID,proto3" json:"ItemID,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	OrderID       string                 `protobuf:"bytes,4,opt,name=OrderID,proto3" json:"OrderID,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=ExpiresAt,proto3" json:"ExpiresAt,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookedItem) Reset() {
	*x = BookedItem{}
	mi := &file_api_oms_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookedItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookedItem) ProtoMessage() {}

func (x *BookedItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_oms_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookedItem.ProtoReflect.Descriptor instead.
func (*BookedItem) Descriptor() ([]byte, []int) {
	return file_api_oms_proto_rawDescGZIP(), []int{9}
}

func (x *BookedItem) GetBookingID() string {
	if x != nil {
		return x.BookingID
	}
	return ""
}

func (x *BookedItem) GetItemID() string {
	if x != nil {
		return x.ItemID
	}
	return ""
}

func (x *BookedItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *BookedItem) GetOrderID() string {
	if x != nil {
		return x.OrderID
	}
	return ""
}

func (x *BookedItem) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *BookedItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type AddStockItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	PriceID       string                 `protobuf:"bytes,4,opt,name=PriceID,proto3" json:"PriceID,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=Description,proto3" json:"Description,omitempty"`
	ImgPath       string                 `protobuf:"bytes,6,opt,name=ImgPath,proto3" json:"ImgPath,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddStockItemRequest) Reset() {
	*x = AddStockItemRequest{}
	mi := &file_api_oms_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddStockItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStockItemRequest) ProtoMessage() {}

func (x *AddStockItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_oms_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStockItemRequest.ProtoReflect.Descriptor instead.
func (*AddStockItemRequest) Descriptor() ([]byte, []int) {
	return file_api_oms_proto_rawDescGZIP(), []int{10}
}

func (x *AddStockItemRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *AddStockItemRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *AddStockItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddStockItemRequest) GetPriceID() string {
	if x != nil {
		return x.PriceID
	}
	return ""
}

func (x *AddStockItemRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddStockItemRequest) GetImgPath() string {
	if x != nil {
		return x.ImgPath
	}
	return ""
}

type AddStockItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *StockItem             `protobuf:"bytes,1,opt,name=Item,proto3" json:"Item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddStockItemResponse) Reset() {
	*x = AddStockItemResponse{}
	mi := &file_api_oms_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddStockItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStockItemResponse) ProtoMessage() {}

func (x *AddStockItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_oms_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStockItemResponse.ProtoReflect.Descriptor instead.
func (*AddStockItemResponse) Descriptor() ([]byte, []int) {
	return file_api_oms_proto_rawDescGZIP(), []int{11}
}

func (x *AddStockItemResponse) GetItem() *StockItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type RemoveStockItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveStockItemRequest) Reset() {
	*x = RemoveStockItemRequest{}
	mi := &file_api_oms_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveStockItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveStockItemRequest) ProtoMessage() {}

func (x *RemoveStockItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_oms_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveStockItemRequest.ProtoReflect.Descriptor instead.
func (*RemoveStockItemRequest) Descriptor() ([]byte, []int) {
	return file_api_oms_proto_rawDescGZIP(), []int{12}
}

func (x *RemoveStockItemRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *RemoveStockItemRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type RemoveStockItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *StockItem             `protobuf:"bytes,1,opt,name=Item,proto3" json:"Item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveStockItemResponse) Reset() {
	*x = RemoveStockItemResponse{}
	mi := &file_api_oms_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveStockItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveStockItemResponse) ProtoMessage() {}

func (x *RemoveStockItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_oms_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveStockItemResponse.ProtoReflect.Descriptor instead.
func (*RemoveStockItemResponse) Descriptor() ([]byte, []int) {
	return file_api_oms_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveStockItemResponse) GetItem() *StockItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type BookItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderID       string                 `protobuf:"bytes,1,opt,name=OrderID,proto3" json:"OrderID,omitempty"`
	Items         []*ItemWithQuantity    `protobuf:"bytes,2,rep,name=Items,proto3" json:"Items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookItemsRequest) Reset() {
	*x = BookItemsRequest{}
	mi := &file_api_oms_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookItemsRequest) ProtoMessage() {}

func (x *BookItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_oms_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookItemsRequest.ProtoReflect.Descriptor instead.
func (*BookItemsRequest) Descriptor() ([]byte, []int) {
	return file_api_oms_proto_rawDescGZIP(), []int{14}
}

func (x *BookItemsRequest) GetOrderID() string {
	if x != nil {
		return x.OrderID
	}
	return ""
}

func (x *BookItemsRequest) GetItems() []*ItemWithQuantity {
	if x != nil {
		return x.Items
	}
	return nil
}

type BookItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bookings      []*ItemWithQuantity    `protobuf:"bytes,1,rep,name=Bookings,proto3" json:"Bookings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookItemsResponse) Reset() {
	*x = BookItemsResponse{}
	mi := &file_api_oms_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookItemsResponse) ProtoMessage() {}

func (x *BookItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_oms_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookItemsResponse.ProtoReflect.Descriptor instead.
func (*BookItemsResponse) Descriptor() ([]byte, []int) {
	return file_api_oms_proto_rawDescGZIP(), []int{15}
}

func (x *BookItemsResponse) GetBookings() []*ItemWithQuantity {
	if x != nil {
		return x.Bookings
	}
	return nil
}

type ReleaseBookedItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderID       string                 `protobuf:"bytes,1,opt,name=OrderID,proto3" json:"OrderID,omitempty"`
	Items         []*ItemWithQuantity    `protobuf:"bytes,2,rep,name=Items,proto3" json:"Items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseBookedItemsRequest) Reset() {
	*x = ReleaseBookedItemsRequest{}
	mi := &file_api_oms_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseBookedItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseBookedItemsRequest) ProtoMessage() {}

func (x *ReleaseBookedItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_oms_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseBookedItemsRequest.ProtoReflect.Descriptor instead.
func (*ReleaseBookedItemsRequest) Descriptor() ([]byte, []int) {
	return file_api_oms_proto_rawDescGZIP(), []int{16}
}

func (x *ReleaseBookedItemsRequest) GetOrderID() string {
	if x != nil {
		return x.OrderID
	}
	return ""
}

func (x *ReleaseBookedItemsRequest) GetItems() []*ItemWithQuantity {
	if x != nil {
		return x.Items
	}
	return nil
}

type ReleaseBookedItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseBookedItemsResponse) Reset() {
	*x = ReleaseBookedItemsResponse{}
	mi := &file_api_oms_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseBookedItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseBookedItemsResponse) ProtoMessage() {}

func (x *ReleaseBookedItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_oms_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseBookedItemsResponse.ProtoReflect.Descriptor instead.
func (*ReleaseBookedItemsResponse) Descriptor() ([]byte, []int) {
	return file_api_oms_proto_rawDescGZIP(), []int{17}
}

func (x *ReleaseBookedItemsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type VerifyStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ItemWithQuantity    `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyStockRequest) Reset() {
	*x = VerifyStockRequest{}
	mi := &file_api_oms_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyStockRequest) ProtoMessage() {}

func (x *VerifyStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_oms_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyStockRequest.ProtoReflect.Descriptor instead.
func (*VerifyStockRequest) Descriptor() ([]byte, []int) {
	return file_api_oms_proto_rawDescGZIP(), []int{18}
}

func (x *VerifyStockRequest) GetItems() []*ItemWithQuantity {
	if x != nil {
		return x.Items
	}
	return nil
}

type VerifyStockResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	AllAvailable          bool                   `protobuf:"varint,1,opt,name=all_available,json=allAvailable,proto3" json:"all_available,omitempty"`
	MissingOrInsufficient []*ItemWithQuantity    `protobuf:"bytes,2,rep,name=missing_or_insufficient,json=missingOrInsufficient,proto3" json:"missing_or_insufficient,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *VerifyStockResponse) Reset() {
	*x = VerifyStockResponse{}
	mi := &file_api_oms_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyStockResponse) ProtoMessage() {}

func (x *VerifyStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_oms_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyStockResponse.ProtoReflect.Descriptor instead.
func (*VerifyStockResponse) Descriptor() ([]byte, []int) {
	return file_api_oms_proto_rawDescGZIP(), []int{19}
}

func (x *VerifyStockResponse) GetAllAvailable() bool {
	if x != nil {
		return x.AllAvailable
	}
	return false
}

func (x *VerifyStockResponse) GetMissingOrInsufficient() []*ItemWithQuantity {
	if x != nil {
		return x.MissingOrInsufficient
	}
	return nil
}

type GetStockItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockItemRequest) Reset() {
	*x = GetStockItemRequest{}
	mi := &file_api_oms_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockItemRequest) ProtoMessage() {}

func (x *GetStockItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_oms_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockItemRequest.ProtoReflect.Descriptor instead.
func (*GetStockItemRequest) Descriptor() ([]byte, []int) {
	return file_api_oms_proto_rawDescGZIP(), []int{20}
}

func (x *GetStockItemRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type GetStockItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *StockItem             `protobuf:"bytes,1,opt,name=Item,proto3" json:"Item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockItemResponse) Reset() {
	*x = GetStockItemResponse{}
	mi := &file_api_oms_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockItemResponse) ProtoMessage() {}

func (x *GetStockItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_oms_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockItemResponse.ProtoReflect.Descriptor instead.
func (*GetStockItemResponse) Descriptor() ([]byte, []int) {
	return file_api_oms_proto_rawDescGZIP(), []int{21}
}

func (x *GetStockItemResponse) GetItem() *StockItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type FinalizeBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderID       string                 `protobuf:"bytes,1,opt,name=OrderID,proto3" json:"OrderID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeBookingRequest) Reset() {
	*x = FinalizeBookingRequest{}
	mi := &file_api_oms_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeBookingRequest) ProtoMessage() {}

func (x *FinalizeBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_oms_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeBookingRequest.ProtoReflect.Descriptor instead.
func (*FinalizeBookingRequest) Descriptor() ([]byte, []int) {
	return file_api_oms_proto_rawDescGZIP(), []int{22}
}

func (x *FinalizeBookingRequest) GetOrderID() string {
	if x != nil {
		return x.OrderID
	}
	return ""
}

type FinalizeBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeBookingResponse) Reset() {
	*x = FinalizeBookingResponse{}
	mi := &file_api_oms_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeBookingResponse) ProtoMessage() {}

func (x *FinalizeBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_oms_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeBookingResponse.ProtoReflect.Descriptor instead.
func (*FinalizeBookingResponse) Descriptor() ([]byte, []int) {
	return file_api_oms_proto_rawDescGZIP(), []int{23}
}

func (x *FinalizeBookingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_oms_proto protoreflect.FileDescriptor

const file_api_oms_proto_rawDesc = "" +
	"\n" +
	"\rapi/oms.proto\x12\x03api\x1a\x1fgoogle/protobuf/timestamp.proto\"p\n" +
	"\x05Order\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x1e\n" +
	"\n" +
	"customerID\x18\x02 \x01(\tR\n" +
	"customerID\x12\x16\n" +
	"\x06Status\x18\x03 \x01(\tR\x06Status\x12\x1f\n" +
	"\x05Items\x18\x04 \x03(\v2\t.api.ItemR\x05Items\"`\n" +
	"\x04Item\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x1a\n" +
	"\bQuantity\x18\x02 \x01(\x05R\bQuantity\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\x12\x18\n" +
	"\aPriceID\x18\x04 \x01(\tR\aPriceID\">\n" +
	"\x10ItemWithQuantity\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x1a\n" +
	"\bQuantity\x18\x02 \x01(\x05R\bQuantity\"a\n" +
	"\x12CreateOrderRequest\x12\x1e\n" +
	"\n" +
	"customerID\x18\x01 \x01(\tR\n" +
	"customerID\x12+\n" +
	"\x05Items\x18\x02 \x03(\v2\x15.api.ItemWithQuantityR\x05Items\"!\n" +
	"\x0fGetOrderRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\"6\n" +
	"\x14GetUserOrdersRequest\x12\x1e\n" +
	"\n" +
	"customerID\x18\x01 \x01(\tR\n" +
	"customerID\";\n" +
	"\x15GetUserOrdersResponse\x12\"\n" +
	"\x06Orders\x18\x01 \x03(\v2\n" +
	".api.OrderR\x06Orders\"]\n" +
	"\x17PatchOrderStatusRequest\x12\x18\n" +
	"\aorderID\x18\x01 \x01(\tR\aorderID\x12(\n" +
	"\x06status\x18\x02 \x01(\x0e2\x10.api.OrderStatusR\x06status\"\x95\x02\n" +
	"\tStockItem\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x1a\n" +
	"\bQuantity\x18\x02 \x01(\x05R\bQuantity\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\x12\x18\n" +
	"\aPriceID\x18\x04 \x01(\tR\aPriceID\x12 \n" +
	"\vDescription\x18\x05 \x01(\tR\vDescription\x12\x18\n" +
	"\aImgPath\x18\x06 \x01(\tR\aImgPath\x128\n" +
	"\tCreatedAt\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tUpdatedAt\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\"\xec\x01\n" +
	"\n" +
	"BookedItem\x12\x1c\n" +
	"\tBookingID\x18\x01 \x01(\tR\tBookingID\x12\x16\n" +
	"\x06ItemID\x18\x02 \x01(\tR\x06ItemID\x12\x1a\n" +
	"\bQuantity\x18\x03 \x01(\x05R\bQuantity\x12\x18\n" +
	"\aOrderID\x18\x04 \x01(\tR\aOrderID\x128\n" +
	"\tExpiresAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tExpiresAt\x128\n" +
	"\tCreatedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\"\xab\x01\n" +
	"\x13AddStockItemRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x1a\n" +
	"\bQuantity\x18\x02 \x01(\x05R\bQuantity\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\x12\x18\n" +
	"\aPriceID\x18\x04 \x01(\tR\aPriceID\x12 \n" +
	"\vDescription\x18\x05 \x01(\tR\vDescription\x12\x18\n" +
	"\aImgPath\x18\x06 \x01(\tR\aImgPath\":\n" +
	"\x14AddStockItemResponse\x12\"\n" +
	"\x04Item\x18\x01 \x01(\v2\x0e.api.StockItemR\x04Item\"D\n" +
	"\x16RemoveStockItemRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x1a\n" +
	"\bQuantity\x18\x02 \x01(\x05R\bQuantity\"=\n" +
	"\x17RemoveStockItemResponse\x12\"\n" +
	"\x04Item\x18\x01 \x01(\v2\x0e.api.StockItemR\x04Item\"Y\n" +
	"\x10BookItemsRequest\x12\x18\n" +
	"\aOrderID\x18\x01 \x01(\tR\aOrderID\x12+\n" +
	"\x05Items\x18\x02 \x03(\v2\x15.api.ItemWithQuantityR\x05Items\"F\n" +
	"\x11BookItemsResponse\x121\n" +
	"\bBookings\x18\x01 \x03(\v2\x15.api.ItemWithQuantityR\bBookings\"b\n" +
	"\x19ReleaseBookedItemsRequest\x12\x18\n" +
	"\aOrderID\x18\x01 \x01(\tR\aOrderID\x12+\n" +
	"\x05Items\x18\x02 \x03(\v2\x15.api.ItemWithQuantityR\x05Items\"6\n" +
	"\x1aReleaseBookedItemsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"A\n" +
	"\x12VerifyStockRequest\x12+\n" +
	"\x05Items\x18\x01 \x03(\v2\x15.api.ItemWithQuantityR\x05Items\"\x89\x01\n" +
	"\x13VerifyStockResponse\x12#\n" +
	"\rall_available\x18\x01 \x01(\bR\fallAvailable\x12M\n" +
	"\x17missing_or_insufficient\x18\x02 \x03(\v2\x15.api.ItemWithQuantityR\x15missingOrInsufficient\"%\n" +
	"\x13GetStockItemRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\":\n" +
	"\x14GetStockItemResponse\x12\"\n" +
	"\x04Item\x18\x01 \x01(\v2\x0e.api.StockItemR\x04Item\"2\n" +
	"\x16FinalizeBookingRequest\x12\x18\n" +
	"\aOrderID\x18\x01 \x01(\tR\aOrderID\"3\n" +
	"\x17FinalizeBookingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*D\n" +
	"\vOrderStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\r\n" +
	"\tCOMPLETED\x10\x02\x12\f\n" +
	"\bCANCELED\x10\x032\xf6\x01\n" +
	"\fOrderService\x122\n" +
	"\vCreateOrder\x12\x17.api.CreateOrderRequest\x1a\n" +
	".api.Order\x12,\n" +
	"\bGetOrder\x12\x14.api.GetOrderRequest\x1a\n" +
	".api.Order\x12F\n" +
	"\rGetUserOrders\x12\x19.api.GetUserOrdersRequest\x1a\x1a.api.GetUserOrdersResponse\x12<\n" +
	"\x10PatchOrderStatus\x12\x1c.api.PatchOrderStatusRequest\x1a\n" +
	".api.Order2\x89\x04\n" +
	"\fStockService\x12C\n" +
	"\fAddStockItem\x12\x18.api.AddStockItemRequest\x1a\x19.api.AddStockItemResponse\x12:\n" +
	"\tBookItems\x12\x15.api.BookItemsRequest\x1a\x16.api.BookItemsResponse\x12U\n" +
	"\x12ReleaseBookedItems\x12\x1e.api.ReleaseBookedItemsRequest\x1a\x1f.api.ReleaseBookedItemsResponse\x12L\n" +
	"\x0fRemoveStockItem\x12\x1b.api.RemoveStockItemRequest\x1a\x1c.api.RemoveStockItemResponse\x12@\n" +
	"\vVerifyStock\x12\x17.api.VerifyStockRequest\x1a\x18.api.VerifyStockResponse\x12C\n" +
	"\fGetStockItem\x12\x18.api.GetStockItemRequest\x1a\x19.api.GetStockItemResponse\x12L\n" +
	"\x0fFinalizeBooking\x12\x1b.api.FinalizeBookingRequest\x1a\x1c.api.FinalizeBookingResponseB&Z$github.com/kiriyms/oms_go-common/apib\x06proto3"

var (
	file_api_oms_proto_rawDescOnce sync.Once
	file_api_oms_proto_rawDescData []byte
)

func file_api_oms_proto_rawDescGZIP() []byte {
	file_api_oms_proto_rawDescOnce.Do(func() {
		file_api_oms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_oms_proto_rawDesc), len(file_api_oms_proto_rawDesc)))
	})
	return file_api_oms_proto_rawDescData
}

var file_api_oms_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_oms_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_api_oms_proto_goTypes = []any{
	(OrderStatus)(0),                   // 0: api.OrderStatus
	(*Order)(nil),                      // 1: api.Order
	(*Item)(nil),                       // 2: api.Item
	(*ItemWithQuantity)(nil),           // 3: api.ItemWithQuantity
	(*CreateOrderRequest)(nil),         // 4: api.CreateOrderRequest
	(*GetOrderRequest)(nil),            // 5: api.GetOrderRequest
	(*GetUserOrdersRequest)(nil),       // 6: api.GetUserOrdersRequest
	(*GetUserOrdersResponse)(nil),      // 7: api.GetUserOrdersResponse
	(*PatchOrderStatusRequest)(nil),    // 8: api.PatchOrderStatusRequest
	(*StockItem)(nil),                  // 9: api.StockItem
	(*BookedItem)(nil),                 // 10: api.BookedItem
	(*AddStockItemRequest)(nil),        // 11: api.AddStockItemRequest
	(*AddStockItemResponse)(nil),       // 12: api.AddStockItemResponse
	(*RemoveStockItemRequest)(nil),     // 13: api.RemoveStockItemRequest
	(*RemoveStockItemResponse)(nil),    // 14: api.RemoveStockItemResponse
	(*BookItemsRequest)(nil),           // 15: api.BookItemsRequest
	(*BookItemsResponse)(nil),          // 16: api.BookItemsResponse
	(*ReleaseBookedItemsRequest)(nil),  // 17: api.ReleaseBookedItemsRequest
	(*ReleaseBookedItemsResponse)(nil), // 18: api.ReleaseBookedItemsResponse
	(*VerifyStockRequest)(nil),         // 19: api.VerifyStockRequest
	(*VerifyStockResponse)(nil),        // 20: api.VerifyStockResponse
	(*GetStockItemRequest)(nil),        // 21: api.GetStockItemRequest
	(*GetStockItemResponse)(nil),       // 22: api.GetStockItemResponse
	(*FinalizeBookingRequest)(nil),     // 23: api.FinalizeBookingRequest
	(*FinalizeBookingResponse)(nil),    // 24: api.FinalizeBookingResponse
	(*timestamppb.Timestamp)(nil),      // 25: google.protobuf.Timestamp
}
var file_api_oms_proto_depIdxs = []int32{
	2,  // 0: api.Order.Items:type_name -> api.Item
	3,  // 1: api.CreateOrderRequest.Items:type_name -> api.ItemWithQuantity
	1,  // 2: api.GetUserOrdersResponse.Orders:type_name -> api.Order
	0,  // 3: api.PatchOrderStatusRequest.status:type_name -> api.OrderStatus
	25, // 4: api.StockItem.CreatedAt:type_name -> google.protobuf.Timestamp
	25, // 5: api.StockItem.UpdatedAt:type_name -> google.protobuf.Timestamp
	25, // 6: api.BookedItem.ExpiresAt:type_name -> google.protobuf.Timestamp
	25, // 7: api.BookedItem.CreatedAt:type_name -> google.protobuf.Timestamp
	9,  // 8: api.AddStockItemResponse.Item:type_name -> api.StockItem
	9,  // 9: api.RemoveStockItemResponse.Item:type_name -> api.StockItem
	3,  // 10: api.BookItemsRequest.Items:type_name -> api.ItemWithQuantity
	3,  // 11: api.BookItemsResponse.Bookings:type_name -> api.ItemWithQuantity
	3,  // 12: api.ReleaseBookedItemsRequest.Items:type_name -> api.ItemWithQuantity
	3,  // 13: api.VerifyStockRequest.Items:type_name -> api.ItemWithQuantity
	3,  // 14: api.VerifyStockResponse.missing_or_insufficient:type_name -> api.ItemWithQuantity
	9,  // 15: api.GetStockItemResponse.Item:type_name -> api.StockItem
	4,  // 16: api.OrderService.CreateOrder:input_type -> api.CreateOrderRequest
	5,  // 17: api.OrderService.GetOrder:input_type -> api.GetOrderRequest
	6,  // 18: api.OrderService.GetUserOrders:input_type -> api.GetUserOrdersRequest
	8,  // 19: api.OrderService.PatchOrderStatus:input_type -> api.PatchOrderStatusRequest
	11, // 20: api.StockService.AddStockItem:input_type -> api.AddStockItemRequest
	15, // 21: api.StockService.BookItems:input_type -> api.BookItemsRequest
	17, // 22: api.StockService.ReleaseBookedItems:input_type -> api.ReleaseBookedItemsRequest
	13, // 23: api.StockService.RemoveStockItem:input_type -> api.RemoveStockItemRequest
	19, // 24: api.StockService.VerifyStock:input_type -> api.VerifyStockRequest
	21, // 25: api.StockService.GetStockItem:input_type -> api.GetStockItemRequest
	23, // 26: api.StockService.FinalizeBooking:input_type -> api.FinalizeBookingRequest
	1,  // 27: api.OrderService.CreateOrder:output_type -> api.Order
	1,  // 28: api.OrderService.GetOrder:output_type -> api.Order
	7,  // 29: api.OrderService.GetUserOrders:output_type -> api.GetUserOrdersResponse
	1,  // 30: api.OrderService.PatchOrderStatus:output_type -> api.Order
	12, // 31: api.StockService.AddStockItem:output_type -> api.AddStockItemResponse
	16, // 32: api.StockService.BookItems:output_type -> api.BookItemsResponse
	18, // 33: api.StockService.ReleaseBookedItems:output_type -> api.ReleaseBookedItemsResponse
	14, // 34: api.StockService.RemoveStockItem:output_type -> api.RemoveStockItemResponse
	20, // 35: api.StockService.VerifyStock:output_type -> api.VerifyStockResponse
	22, // 36: api.StockService.GetStockItem:output_type -> api.GetStockItemResponse
	24, // 37: api.StockService.FinalizeBooking:output_type -> api.FinalizeBookingResponse
	27, // [27:38] is the sub-list for method output_type
	16, // [16:27] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_api_oms_proto_init() }
func file_api_oms_proto_init() {
	if File_api_oms_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_oms_proto_rawDesc), len(file_api_oms_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_oms_proto_goTypes,
		DependencyIndexes: file_api_oms_proto_depIdxs,
		EnumInfos:         file_api_oms_proto_enumTypes,
		MessageInfos:      file_api_oms_proto_msgTypes,
	}.Build()
	File_api_oms_proto = out.File
	file_api_oms_proto_goTypes = nil
	file_api_oms_proto_depIdxs = nil
}
